<a href="https://colab.research.google.com/github/acharyariku/PyTorch-Training/blob/main/PyTorch_Exercise_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
tensor = torch.rand(7,7)
tensor

tensor([[0.2811, 0.3587, 0.5821, 0.1174, 0.3021, 0.6328, 0.0362],
        [0.9984, 0.5674, 0.6226, 0.1086, 0.2157, 0.3358, 0.7771],
        [0.1686, 0.8762, 0.5631, 0.3891, 0.1337, 0.2221, 0.0459],
        [0.8635, 0.1549, 0.6671, 0.0517, 0.4993, 0.9943, 0.1756],
        [0.0491, 0.8783, 0.6744, 0.4772, 0.2182, 0.6521, 0.7070],
        [0.0265, 0.5652, 0.1660, 0.4550, 0.2156, 0.8768, 0.1328],
        [0.2290, 0.1700, 0.3528, 0.1784, 0.6719, 0.3822, 0.1720]])

In [ ]:
tensor2 = torch.rand(1,7)
tensor2

tensor([[0.3302, 0.3063, 0.3043, 0.3819, 0.4786, 0.6470, 0.4214]])

In [ ]:
ans = tensor @ tensor2.T
ans, ans.shape

(tensor([[0.9939],
         [1.3823],
         [0.8710],
         [1.5115],
         [1.4970],
         [1.1326],
         [0.9445]]),
 torch.Size([7, 1]))

In [ ]:
torch.manual_seed(0)

tensor1 = torch.rand(7,7)
tensor2 = torch.rand(1,7)

ans = tensor1 @ tensor2.T
ans, ans.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [ ]:
torch.cuda.manual_seed_all(1234)

In [ ]:
device = 'cpu'
if torch.cuda.is_available():
  device = 'cuda'

In [ ]:
tensor1 = torch.rand(2,3,device=device)
tensor2 = torch.rand(2,3,device=device)

In [ ]:
ans = tensor1 @ tensor2.T
ans

tensor([[0.6407, 0.5931],
        [0.5043, 0.6066]], device='cuda:0')

In [ ]:
torch.max(ans),torch.min(ans)

(tensor(0.6407, device='cuda:0'), tensor(0.5043, device='cuda:0'))

In [ ]:
torch.argmax(ans),torch.argmin(ans)

(tensor(0, device='cuda:0'), tensor(2, device='cuda:0'))

In [ ]:
torch.cuda.manual_seed_all(7)
a = torch.rand(1,1,1,10)
torch.cuda.manual_seed_all(7)
b = torch.squeeze(a)
a , a.shape, b, b.shape

(tensor([[[[0.5191, 0.6159, 0.8102, 0.9801, 0.1147, 0.3168, 0.6965, 0.9143,
            0.9351, 0.9412]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5191, 0.6159, 0.8102, 0.9801, 0.1147, 0.3168, 0.6965, 0.9143, 0.9351,
         0.9412]),
 torch.Size([10]))