<a href="https://colab.research.google.com/github/acharyariku/PyTorch-Training/blob/main/PyTorch_Tutorial00_GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [ ]:
torch.cuda.device_count()

1

In [ ]:
torch.backends.mps.is_available()

False

In [ ]:
device

'cuda'

In [ ]:
tensor = torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])